Sistema de Alerta
Maloca-iCoisas/maloca-turma-ufrr-2023 pull request #1
Opened 2024-11-02 14:09 UTC by Luccas-H

# Pull Request - Projeto Maloca das iCoisas

## Descrição do Pull Request

### O que foi implementado:
Sistema de alerta baseado em um circuito que funciona inicialmente com um botão que ao ser pressionado gera o estado de alerta.

### Contexto e Motivação:
Circuito que funciona com foco em auxiliar pessoas/pacientes que necessitam de supervisionamento.

## Testes Realizados

### Descrição dos Testes:
1. Verifique se ao pressionar o botão o led(verde) irá apagar e se o led(vermelho) começará a piscar. Além disso, verifique se ao pressionar o botão a mensagem no LCD irá mudar;
2.  Verifique se após o led(vermelhor) apagar o LCD volte para o padrão e se o led(verde) liga novamente.

### Resultados dos Testes:
O sistema apresentou pleno funcionamento sem nenhum impasse.

## Checklist

- [x] Código atende às normas do projeto e foi formatado de acordo com as diretrizes.
- [x] Código foi testado e validado em ambiente de desenvolvimento com hardware real (Arduino, Raspberry Pi, ESP32) ou simulação (tinkercad).
- [x] Documentação atualizada para refletir as mudanças realizadas.
- [x] Código escrito e comentado em **C** ou **Python** de acordo com os padrões do projeto.
- [x] Testes com sensores e atuadores específicos incluídos e detalhados na descrição dos testes.

## Tipo de Mudança

- [ ] Correção de bug
- [x] Nova funcionalidade
- [ ] Alteração de funcionalidade existente
- [x] Documentação

## Informações Adicionais

### Hardware Utilizado:
1. Placa Arduino Mega ou Mega2560;
2.  PushButton;
3.  Led's (Vermelho; Verde);
4.  LCD;
5.  Resistores (3 de 330 ohms; 2 de 1kohms);
6.  Jumpers.

### Simulação Utilizado:
- Link da simulação: https://www.tinkercad.com/things/1unuX2OeU4X

### Observações:
Se atentar ao interligar os componentes, principalmente o LCD.
---

2024-11-05 21:01 UTC, hbgit requested changes
Olá,

Agradecemos muito pela sua contribuição! Antes de finalizar, pedimos que revise alguns pontos específicos para melhorar a clareza e a completude do tutorial do **Sistema de Alerta**. Abaixo, seguem as nossas considerações:

- **Título**: Sugerimos alterar o nome do tutorial para refletir mais precisamente a funcionalidade e a finalidade do sistema de alerta. Por que este sistema é importante? Qual problema ele resolve?
  
- **Link para o Tinkercad**: O link atual para o Tinkercad parece estar inativo. Por favor, verifique e atualize o link. Além disso, seria ideal incluir o link diretamente no corpo do tutorial, para facilitar o acesso.

- **Correções de formatação**: Na seção onde estão listados os componentes, há um pequeno erro de formatação, como em "Protoboar<d(>fins educacionais)". Ajuste para "Protoboard (fins educacionais)" e verifique se há outros itens com formatação similar para corrigir.

- **Especificação dos Pinos**: Na seção **"Montagem do Circuito"**, é importante detalhar em quais pinos estão conectados cada componente. Esse nível de detalhe ajuda o usuário a replicar o circuito com precisão e evita confusões.

- **Comentários no Código**: Na seção **"Passo 2: Lógica do Sistema de Alerta"**, recomendamos adicionar comentários no código para explicar cada parte da lógica. Isso tornará o tutorial mais acessível, especialmente para iniciantes, permitindo que compreendam a lógica por trás do sistema.

Por gentileza, implemente essas sugestões para tornar o tutorial ainda mais claro e completo. Muito obrigado!

2024-11-05 21:17 UTC, Luccas-H commented
Ciente, realizarei as mudanças !!

2024-11-05 23:03 UTC, Luccas-H commented
Alterações realizadas conforme o que foi pedido, assim aguardo pela avaliação !!

2024-11-06 13:08 UTC, hbgit approved these changes
As modificações solicitadas foram aplicadas.

2024-11-06 13:09 UTC, merged