Monitoramento De Umidade Para Doenças Respiratórias.
Maloca-iCoisas/maloca-turma-ufrr-2023 pull request #11
Opened 2024-11-16 18:22 UTC by ArthurRamos26

# Pull Request - Projeto Maloca das iCoisas

## Descrição do Pull Request

### O que foi implementado:

- 

### Contexto e Motivação:

- 

## Testes Realizados

### Descrição dos Testes:

- 

### Resultados dos Testes:

- 

## Checklist

- [ ] Código atende às normas do projeto e foi formatado de acordo com as diretrizes.
- [ ] Código foi testado e validado em ambiente de desenvolvimento com hardware real (Arduino, Raspberry Pi, ESP32) ou simulação (tinkercad).
- [ ] Documentação atualizada para refletir as mudanças realizadas.
- [ ] Código escrito e comentado em **C** ou **Python** de acordo com os padrões do projeto.
- [ ] Testes com sensores e atuadores específicos incluídos e detalhados na descrição dos testes.

## Tipo de Mudança

- [ ] Correção de bug
- [ ] Nova funcionalidade
- [ ] Alteração de funcionalidade existente
- [ ] Documentação

## Informações Adicionais

### Hardware Utilizado:

- 

### Simulação Utilizado:

-

### Observações:

- 

## Issue Relacionada

Closes #

---

**Nota:** Certifique-se de que o código e as descrições estejam claros e detalhados o suficiente para uma revisão eficaz.

2024-11-18 20:37 UTC, hbgit requested changes
Olá,

Agradecemos muito pela sua contribuição! Antes de finalizarmos, pedimos que revise alguns pontos específicos para melhorar a clareza e a completude do tutorial. Abaixo seguem as nossas considerações:

- Criar uma pasta especifica para o seu tutorial dentro de tutoriais, onde deve conter todos os seus arquivos. O arquivo com extensão .md deve ter o nome README.

Por gentileza, implemente essas sugestões para tornar o tutorial ainda mais claro e completo. Agradecemos novamente pela sua dedicação e contribuição para o projeto!

2024-11-22 04:36 UTC, ArthurRamos26 reviewed
.

2024-12-05 18:03 UTC, hbgit requested changes

2024-12-05 18:03 UTC, hbgit commented on tutoriais/modelo-tutorial.md
Este arquivo não pode ser removido, por favor, adicionar novamente e atualizar o seu branch com o principal do projeto

2024-12-06 13:54 UTC, hbgit approved these changes
alterações implementadas

2024-12-06 13:54 UTC, merged