sistema de estoque de farmacia
Maloca-iCoisas/maloca-turma-ufrr-2023 pull request #6
Opened 2024-11-15 02:29 UTC by Moab76

# Pull Request - Projeto Maloca das iCoisas

## Descrição do Pull Request

### O que foi implementado:

- 

### Contexto e Motivação:

- 

## Testes Realizados

### Descrição dos Testes:

- 

### Resultados dos Testes:

- 

## Checklist

- [ ] Código atende às normas do projeto e foi formatado de acordo com as diretrizes.
- [ ] Código foi testado e validado em ambiente de desenvolvimento com hardware real (Arduino, Raspberry Pi, ESP32) ou simulação (tinkercad).
- [ ] Documentação atualizada para refletir as mudanças realizadas.
- [ ] Código escrito e comentado em **C** ou **Python** de acordo com os padrões do projeto.
- [ ] Testes com sensores e atuadores específicos incluídos e detalhados na descrição dos testes.

## Tipo de Mudança

- [ ] Correção de bug
- [ ] Nova funcionalidade
- [ ] Alteração de funcionalidade existente
- [ ] Documentação

## Informações Adicionais

### Hardware Utilizado:

- 

### Simulação Utilizado:

-

### Observações:

- 

## Issue Relacionada

Closes #

---

**Nota:** Certifique-se de que o código e as descrições estejam claros e detalhados o suficiente para uma revisão eficaz.

2024-11-18 20:27 UTC, hbgit requested changes
Olá @Moab76 ,

Agradecemos muito pela sua contribuição! Antes de finalizarmos, pedimos que revise alguns pontos específicos para melhorar a clareza e a completude do tutorial. Abaixo seguem as nossas considerações:

- Criar uma pasta especifica para o seu tutorial dentro de tutoriais, onde deve conter todos os seus arquivos. O arquivo com extensão .md deve ter o nome README.

Por gentileza, implemente essas sugestões para tornar o tutorial ainda mais claro e completo. Agradecemos novamente pela sua dedicação e contribuição para o projeto!

2024-11-18 22:32 UTC, Moab76 commented
alterações feitas

2024-11-28 14:09 UTC, Moab76 commented
correções feitas, link da simulção e comentario no código.

2024-12-05 17:19 UTC, hbgit approved these changes

2024-12-05 17:20 UTC, merged